### ISSUE TITLE
Host discovery breaks due to missing host parameters

### ISSUE THREAD

**Issue by laugmanuel** [dm-drogeriemarkt/foreman_git_templates#59]
When [foreman_discovery](https://github.com/theforeman/foreman_discovery) is used, the discovery fails and shows an error on the host's console:
```
500: Discovery failed, code 422, reason: undefined method 'params' for #<Host::Discovered::0x00007facce1938e0> 
```
On the smartproxy:
```
2020-06-18T08:46:02 4d157ad9 [W] Discovery failed, code 422, reason: undefined method `params' for #<Host::Discovered:0x00007facce1938e0>
RuntimeError: Discovery failed, code 422, reason: undefined method `params' for #<Host::Discovered:0x00007facce1938e0>
/usr/share/gems/gems/smart_proxy_discovery-1.0.5/lib/smart_proxy_discovery/discovery_main.rb:18:in `create_discovered_host'
/usr/share/gems/gems/smart_proxy_discovery-1.0.5/lib/smart_proxy_discovery/discovery_api.rb:38:in `block in <class:InboundApi>'
[...]
```
We also see the matching error in Foreman itself:
```
NoMethodError: ********
  from active_model/attribute_methods.rb:430:in `method_missing'
  from audited/auditor.rb:99:in `method_missing'
  from foreman_git_templates/orchestration/tftp.rb:23:in `validate_tftp'
  from active_support/callbacks.rb:426:in `block in make_lambda'
[...]
```
The error is probably caused by this call for `params` on `Host::Discovered` which does not exist:
https://github.com/dm-drogeriemarkt/foreman_git_templates/blob/caa1cc6a3b46651fe88e9edeb3d93e527033a435/app/models/concerns/foreman_git_templates/orchestration/tftp.rb#L23

Adding a check solves the problem:
```ruby
def validate_tftp
    return super unless host.managed
    return super unless host.params['template_url']
    [...]
end
```

**Comment by laugmanuel** [comment]
With 1.0.5 there seems to be another problem:
Opening "Discovered hosts" in the GUI causes the following error:
```
ActionView::Template::Error
undefined method `repository_path' for #<Host::Discovered:0x00007fd9617030b8>
/opt/theforeman/tfm-ror52/root/usr/share/gems/gems/activemodel-5.2.1/lib/active_model/attribute_methods.rb:430:in `method_missing'
/opt/theforeman/tfm/root/usr/share/gems/gems/audited-4.9.0/lib/audited/auditor.rb:99:in `method_missing'
/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_git_templates-1.0.5/app/helpers/foreman_git_templates/application_helper.rb:11:in `display_link_if_authorized'
/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_discovery-16.0.1/app/helpers/discovered_hosts_helper.rb:21:in `block in discovered_hosts_title_actions'
[...]
```

**Comment by timogoebel** [comment]
Can we add the extensions to `Host::Managed`?

**Comment by timogoebel** [comment]
What I mean is:
- `host.managed` (or better `host.managed?` - rails automatically adds a method with the `?` extension for boolean parameters) is a parameter on the host object. It checks if the host should be managed via Foreman or not.
- `Host::Managed` is misleading. This means a "normal" host. `Host::Discovered` is not a "normal" host, e.g. it's not a `Host::Managed`.
- A `Host::Managed` can be `managed: true` and `managed: false`.
- So we should either add the extensions to `Host::Managed` and not `Host::Base` or check something like `return unless is_a?(Host::Managed)`

**Comment by laugmanuel** [comment]
You are right.
Checking for `host.managed?` does work in this case but only because the attribute is present on `Host::Managed` (e.g. a "normal" host) but not on `Host::Discovered` (a "discovered" one) - this check would also _work_ with any other attribute not present on `Host::Discovered`.

I like the idea of `return unless is_a?(Host::Managed)` - but I'm not really sure if this would be best practice here.
